services:
  - type: web
    name: nebula-chat-server
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx turbo run build --filter=@nebula/chat-server
    startCommand: npx turbo run start --filter=@nebula/chat-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: PORT
        value: 9001
